apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: enterprise

  template:
    metadata:
      labels:
        app: enterprise

    spec:
      containers:
        - name: enterprise-container
          image: enterprise-nginx:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 80